name       : python-jsonrpc-server
version    : 0.4.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/python-jsonrpc-server/python-jsonrpc-server-0.4.0.tar.gz : 62c543e541f101ec5b57dc654efc212d2c2e3ea47ff6f54b2e7dcb36ecf20595
homepage   : https://github.com/palantir/python-jsonrpc-server
license    : MIT
component  : programming.python
summary    : Python library implementing asynchronous JSON RPC server
description: |
    Python library implementing asynchronous JSON RPC server
builddeps  :
    - pycodestyle
    - pyflakes
    - pylint
    - python-mock
    - python-pytest-cov
    - python-ujson
rundeps    :
    - python-ujson
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test py.test3 -v
